### PR TITLE
:sparkles: feat: add responsive playbar styles

### PR DESCRIPTION
**Pull request by wakeupaj**
# Pull request for issue #2 

Keep in mind, I don't know how to test this, but if you could attempt to would be great.

### CODE REVIEW

**Comment by sanoojes** [comment]
Thank you for adding the PR to fix this! I haven't been maintaining it due to time constraints. I tested your fix, but this behavior is unintended with the theme. 

**Before the fix:** 

https://github.com/user-attachments/assets/0c2aec2f-6a33-49ef-8f88-02fe90d8189c

**After the fix:**

https://github.com/user-attachments/assets/43f1b455-f926-4176-bcc1-03f0c557356b

**Comment by sanoojes** [comment]
no idea why it has no preview 🚶

**Comment by sanoojes** [comment]
What about this?  https://gist.github.com/sanoojes/392e3780eeefecb34555f5355341a263

https://github.com/user-attachments/assets/7a07a699-2be3-4f35-943c-fd69d1a13b16

**Comment by wakeupaj** [comment]
> What about this? https://gist.github.com/sanoojes/392e3780eeefecb34555f5355341a263
> 2024-09-17.11-43-51.mp4

this is exactly how i imagined it. thank you for the quick fix, have you pushed the change? should i be able to update it withint spicetify now?

**Comment by sanoojes** [comment]
> > What about this? https://gist.github.com/sanoojes/392e3780eeefecb34555f5355341a263
> > 2024-09-17.11-43-51.mp4
> 
> this is exactly how i imagined it. thank you for the quick fix, have you pushed the change? should i be able to update it withint spicetify now?

no i didnt push it i will edit this pr and add it

**Pull request merged**
